language: php
# sudo to install imagemagick
sudo: true

php:
  - 5.6

branches:
  except:
    - 7.x-1.x

addons:
  firefox: "29.0"

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  - UPGRADE=none
#  - UPGRADE=7.x-2.38
#  - UPGRADE=7.x-2.37
#  - UPGRADE=7.x-2.36
#  - UPGRADE=7.x-2.35
#  - UPGRADE=7.x-2.34
#  - UPGRADE=7.x-2.33
#  - UPGRADE=7.x-2.32
#  - UPGRADE=7.x-2.31
#  - UPGRADE=7.x-2.30
#  - UPGRADE=7.x-2.29
#  - UPGRADE=7.x-2.28
#  - UPGRADE=7.x-2.27
#  - UPGRADE=7.x-2.26
#  - UPGRADE=7.x-2.25

#matrix:
#  fast_finish: true
#  include:
#    - php: 5.5
#      env: UPGRADE=none
#    - php: 5.5
#      env: UPGRADE=7.x-2.23 TEST_FEATURES_OVERRIDES=1
#    - php: 7.0
#      env: UPGRADE=none
#    - php: hhvm
#      env: UPGRADE=none
#  allow_failures:
#    - php: 7.0
#    - php: hhvm

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache
    - tests/behat/vendor

install:
  # Remove xdebug for the moment. We aren't generating code coverage, and it slows us down.
  - rm /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini

  # Create database.
  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Drupal.org verify tool
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # Build Behat dependencies
  - cd ./tests/behat
  - travis_retry composer install --prefer-dist --no-interaction
  - cd ../../../

  # Setting Behat environment
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - BEHAT_PARAMS='{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"BUILD_TOP/drupal"}}}}'
  - BEHAT_PARAMS=`echo $BEHAT_PARAMS | sed -e s#BUILD_TOP#$BUILD_TOP#`
  - export BEHAT_PARAMS

  # Install imagemagick
  - sudo apt-get install -y imagemagick

  # Build baseline site
  - drush dl commerce_kickstart --drupal-project-rename=commerce_kickstart_baseline

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv commerce_kickstart profiles/
  - mkdir drupal
  - mv profiles drupal/

  # Build the current branch
  - cd drupal
  - drush make --yes profiles/commerce_kickstart/drupal-org-core.make --prepare-install
  - drush make --yes profiles/commerce_kickstart/drupal-org.make --no-core --contrib-destination=profiles/commerce_kickstart
  # Download Diff module for checking overridden features through Drush.
  - drush dl diff
  - cd ../

  # Verify that all the .make files will work on Drupal.org.
  - drush verify-makefile drupal/profiles/commerce_kickstart/drupal-org.make
  - find drupal/profiles/commerce_kickstart/modules -name \*.make -print0 | xargs -0 -n1 drush verify-makefile

  # Download an old version to test upgrading from.
  - if [[ "$UPGRADE" != none ]]; then drush dl commerce_kickstart-$UPGRADE; fi

  # Setup files
  - chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
  - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 5; done

   # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Multibyte string input conversion in PHP is active and must be disabled for Drupal on PHP 5.6.
  - echo "mbstring.http_input = pass" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "mbstring.http_output = pass" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

  # Enable APC
  - |
    if [[ $TRAVIS_PHP_VERSION < "5.5" ]]; then
      echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      echo "apc.shm_size=256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi

before_script:

  # Start baseline site(Correct version of the site) at http://127.0.0.1:7777/
  - cd commerce_kickstart_baseline
  - drush si commerce_kickstart --db-url=mysql://root:@127.0.0.1/drupal_baseline --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce Kickstart" --yes -v -d
  - drush pm-disable dblog --yes
  - drush runserver --server=builtin 7777 > /dev/null 2>&1 &
  - nc -zvv localhost 7777; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 7777..."; nc -zvv localhost 7777; out=$?; sleep 5; done
  - cd ..

  # Do the site install (either the current revision or old for the upgrade).
  - if [[ "$UPGRADE" == none ]]; then cd drupal; else cd commerce_kickstart-$UPGRADE; fi


  # Copy override module into sites/default/modules so it carries over when testing upgrades.
  - if [[ "$TEST_FEATURES_OVERRIDES" == 1 ]]; then mkdir sites/default/modules && cp -r ../drupal/profiles/commerce_kickstart/tests/commerce_kickstart_overrides_test sites/default/modules/commerce_kickstart_overrides_test; fi

  - drush si commerce_kickstart --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce Kickstart" --yes
  - drush pm-disable dblog --yes

  # If testing the override, enable it and revert feature it's overriding (because we didn't on the same install.)
  # We need to download rc2, because rc3 requires a function in Features 2.7,
  # breaking test.
  - if [[ "$TEST_FEATURES_OVERRIDES" == 1 ]]; then drush dl features_override-7.x-2.0-rc2 && drush en -y commerce_kickstart_overrides_test && drush fr -y commerce_kickstart_blog; fi

  - cd ../drupal

  # If we're an upgrade test, run the upgrade process.
  - if [[ "$UPGRADE" != none ]]; then cp -a ../commerce_kickstart-$UPGRADE/sites/default/* sites/default/ && drush updb --yes; drush cc all;  fi

  # Start server(Test version of the site) at http://127.0.0.1:8888/
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 5; done
  - cd profiles/commerce_kickstart/tests/behat

  # Introduce visual difference by disabling the blog module
  #- drush dis commerce_kickstart_blog -y

  #Setup Drulenium
  - drush dl drulenium-7.x-2.x-dev -y
  - drush en libraries -y
  - drush en drulenium drulenium_local_selenium drulenium_hosting_client -y
  - drush vr-download-webdriver
  - drush vset --yes drulenium_vr_config_server_opt 'drulenium_local_selenium'
  - drush vset --yes drulenium_vr_config_image_server_opt 'local'
  - drush vset --yes drulenium_vr_release_imagemagick_path '/usr/bin'
  - drush vset --yes drulenium_vr_api_secret $DRULENIUM_ORG_API_SECRET -q
  - drush dl drulenium_imgur-7.x-1.x-dev
  - drush en drulenium_imgur -y
  - drush imgur-download-client -y
  - drush vset --yes drulenium_imgur_client_id $IMGUR_CLIENT_ID -q
  - drush vset --yes drulenium_imgur_client_secret $IMGUR_CLIENT_SECRET -q
  # Test as admin user
  - drush vset --yes drulenium_vr_release_user_name 'admin' -q
  - drush vset --yes drulenium_vr_release_user_pass 'admin' -q

script:

  # If this isn't an upgrade, we test if any features are overridden.
  - if [[ "$UPGRADE" == none ]]; then ../../scripts/check-overridden.sh; fi

  # Fix bad Commerce Migrate release for testing the demo.
  - if [[ "$UPGRADE" == "7.x-2.34" || "$UPGRADE" == "7.x-2.33" || "$UPGRADE" == "7.x-2.32" || "$UPGRADE" == "7.x-2.31" || "$UPGRADE" == "7.x-2.30" || "$UPGRADE" == "7.x-2.29" || "$UPGRADE" == "7.x-2.28" || "$UPGRADE" == "7.x-2.27" ]]; then drush mi --all --update; fi

  # Run Behat tests.
  #- if [[ "$TEST_FEATURES_OVERRIDES" != 1 ]]; then ./bin/behat --config behat.travis.yml --tags ~@overrides; fi
  #- if [[ "$TEST_FEATURES_OVERRIDES" == 1 ]]; then ./bin/behat --config behat.travis.yml --tags @overrides; fi

  # Getting commit message: https://github.com/travis-ci/travis-ci/issues/965
  # https://github.com/twbs/bootstrap/blob/e3f4072a9e1f1163c5b7b6a52d9b2632569f90fb/.travis.yml#L9
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - echo "$TRAVIS_COMMIT_MSG"

  # Import Drulenium tests
  - export TEST_PAGES=$(echo `curl -s http://drulenium.org/api/v1/project/$DRULENIUM_ORG_PROJECT_UUID | jq -r '.tests | join(",")'`)
  - echo "$TEST_PAGES";
  - IFS=',' read -ra ADDR <<< "$TEST_PAGES"
  - for i in "${ADDR[@]}"; do drush vr-test-import $i travis-regression; done

  # Run Drulenium tests.
  - drush vrc "http://127.0.0.1:7777/" "$TRAVIS_COMMIT_MSG" --preset_category=travis-regression
  - drush vrc "http://127.0.0.1:8888/" "$TRAVIS_COMMIT_MSG" --preset_category=travis-regression
  - drush vr-diff --preset_category=travis-regression
  - drush vr-diff-upload --preset_category=travis-regression --project_id=$DRULENIUM_ORG_PROJECT_UUID

notifications:

  irc: "chat.freenode.net#drupal-commerce"
